format = """
$username@$hostname $directory $git_branch
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[username]
style_user = "bold #8abeb7"
style_root = "bold #cc6666"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold #f0c674)"
disabled = false

[directory]
format = "[$path]($style)"
style = "bold #81a2be"

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style)"
